### Requisição para a raiz
GET http://localhost:5194/

### Listar todos os produtos
GET http://localhost:5194/api/produto/listar

### Cadastrar o produto
POST http://localhost:5194/api/produto/cadastrar
Content-Type: application/json

{
    "nome" : "Mouse",
    "descricao" : "Logitech",
    "quantidade" : 12,
    "preco" : 300
}



### Buscar um produto pelo id
GET http://localhost:5194/api/produto/buscar/2474d1de-6b8f-4ec9-94f1-2643e54dd187

### Remover um produto
DELETE  http://localhost:5194/api/produto/remover/2474d1de-6b8f-4ec9-94f1-2643e54dd187

###Alterar um produto

PATCH  http://localhost:5194/api/produto/alterar/2474d1de-6b8f-4ec9-94f1-2643e54dd187
Content-Type: application/json

{
    "nome" : "Pc gamer",
    "quantidade" : 10,
    "preco" : 2000
}